user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

sms:
    resource: "@SMSBundle/Controller/"
    type:     annotation
    prefix:   /



event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

enfants:
    resource: "@EnfantsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"